service: triggerTest

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: xci-serverlesss-test
          event: s3:ObjectCreated:*
          
resources:
  Resources:
    HelloLambdaPermissionS3:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName: 
          "Fn::GetAtt":
            - HelloLambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::xci-serverlesss-test"